// <auto-generated />
using System;
using DigitalHub.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalHub.Migrations
{
    [DbContext(typeof(MyDataContext))]
    [Migration("20240117144637_secound_migration")]
    partial class secound_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalHub.Models.Assessment_Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Score")
                        .HasColumnType("tinyint");

                    b.Property<int?>("assessment_id")
                        .HasColumnType("int");

                    b.Property<int?>("question_id")
                        .HasColumnType("int");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("assessment_id");

                    b.HasIndex("question_id");

                    b.HasIndex("user_id");

                    b.ToTable("Assessment_Answers");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessment_Options", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Correct")
                        .HasColumnType("tinyint");

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("question_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("question_id");

                    b.ToTable("Assessment_Options");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessment_Questions_Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("assesment_id")
                        .HasColumnType("int");

                    b.Property<int?>("question_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("assesment_id");

                    b.HasIndex("question_id");

                    b.ToTable("Assessment_Questions_Relations");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessment_True_False", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Is_true")
                        .HasColumnType("bit");

                    b.Property<int?>("question_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("question_id");

                    b.ToTable("Assessment_True_Falses");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessment_enrols", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<int?>("assessment_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.HasIndex("assessment_id");

                    b.ToTable("Assessment_Enrols");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessment_text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orer")
                        .HasColumnType("int");

                    b.Property<int?>("question_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("question_id");

                    b.ToTable("Assessment_Texts");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessments_Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Assessments_Questions");
                });

            modelBuilder.Entity("DigitalHub.Models.Assesstment_Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("question_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("question_id");

                    b.ToTable("Assesstment_Matches");
                });

            modelBuilder.Entity("DigitalHub.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessment_Answer", b =>
                {
                    b.HasOne("DigitalHub.Models.Assessments", "Assessments")
                        .WithMany()
                        .HasForeignKey("assessment_id");

                    b.HasOne("DigitalHub.Models.Assessments_Questions", "Assessments_Questions")
                        .WithMany()
                        .HasForeignKey("question_id");

                    b.HasOne("DigitalHub.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("Assessments");

                    b.Navigation("Assessments_Questions");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessment_Options", b =>
                {
                    b.HasOne("DigitalHub.Models.Assessments_Questions", "Assessments_Questions")
                        .WithMany()
                        .HasForeignKey("question_id");

                    b.Navigation("Assessments_Questions");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessment_Questions_Relation", b =>
                {
                    b.HasOne("DigitalHub.Models.Assessments", "Assessments")
                        .WithMany("Assessment_Questions_Relations")
                        .HasForeignKey("assesment_id");

                    b.HasOne("DigitalHub.Models.Assessments_Questions", "Assessments_Questions")
                        .WithMany("Assessment_Questions_Relations")
                        .HasForeignKey("question_id");

                    b.Navigation("Assessments");

                    b.Navigation("Assessments_Questions");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessment_True_False", b =>
                {
                    b.HasOne("DigitalHub.Models.Assessments_Questions", "Assessments_Questions")
                        .WithMany()
                        .HasForeignKey("question_id");

                    b.Navigation("Assessments_Questions");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessment_enrols", b =>
                {
                    b.HasOne("DigitalHub.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_id");

                    b.HasOne("DigitalHub.Models.Assessments", "Assessments")
                        .WithMany()
                        .HasForeignKey("assessment_id");

                    b.Navigation("Assessments");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessment_text", b =>
                {
                    b.HasOne("DigitalHub.Models.Assessments_Questions", "Assessments_Questions")
                        .WithMany()
                        .HasForeignKey("question_id");

                    b.Navigation("Assessments_Questions");
                });

            modelBuilder.Entity("DigitalHub.Models.Assesstment_Match", b =>
                {
                    b.HasOne("DigitalHub.Models.Assessments_Questions", "Assessments_Questions")
                        .WithMany()
                        .HasForeignKey("question_id");

                    b.Navigation("Assessments_Questions");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessments", b =>
                {
                    b.Navigation("Assessment_Questions_Relations");
                });

            modelBuilder.Entity("DigitalHub.Models.Assessments_Questions", b =>
                {
                    b.Navigation("Assessment_Questions_Relations");
                });
#pragma warning restore 612, 618
        }
    }
}
